name: Automated Blog Generator

on:
  schedule:
    # Runs every Tuesday and Friday at 9:00 AM UTC
    - cron: '0 9 * * 2,5'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set timezone
      run: |
        sudo timedatectl set-timezone Asia/Kolkata
    
    - name: Create .env file from secrets
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
        echo "PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY }}" >> .env
        echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env
        echo "PEXELS_API_KEY=${{ secrets.PEXELS_API_KEY }}" >> .env
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
        echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
    
    - name: Run blog generator
      run: |
        python -c "from blog_generator import generate_blog_post; generate_blog_post()"
    
    - name: Upload logs as artifacts (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: blog-generator-logs
        path: blog_generator.log
        retention-days: 7
